### ISSUE TITLE
Examples break with newer django

### ISSUE THREAD

**Issue by Z0t** [rayed/django-crud-parent-child#1]
I know this is 2 years old, but there are several braking changes in Django that need to be addressed for the examples to work:

https://docs.djangoproject.com/en/dev/releases/1.9/#passing-a-3-tuple-or-an-app-name-to-include

1) django.core.urlresolvers is deprecated (> 1.11).  "from django.conf.urls import patterns, url" need to be changed to "from django.conf.urls import include, url" or "from django.conf.urls import include, url" and "from django.conf.urls import patterns, url" to "from django.conf.urls import url" 

2) The include pattern has to change per 
The main site file urls.py need change all of the include lines, just remove '.nameane='[app_name]).

The urls.py in each app directory merely need to have app_name ='[app_name]' added

Affected files:

./apps/urls.py
./books_pc_formset/urls.py
./books_pc_formset2/urls.py
./books_pc_multi_view/urls.py
./books_pc_multi_view2/urls.py
./books_simple/urls.py

https://docs.djangoproject.com/en/dev/releases/1.9/#foreignkey-and-onetoonefield-on-delete-argument

3) on_delete is required for all foreign keys (Djanago 2.0).  

Adding on_delete=models.CASCADE preserves the default behavior:

books_pc_formset/models.py:    book = models.ForeignKey(Book,on_delete=models.CASCADE)
books_pc_formset2/models.py:    book = models.ForeignKey(Book,on_delete=models.CASCADE)
books_pc_formset2/models.py:    person = models.ForeignKey(Person,on_delete=models.CASCADE)
books_pc_multi_view/models.py:    book = models.ForeignKey(Book,on_delete=models.CASCADE)
books_pc_multi_view2/models.py:    book = models.ForeignKey(Book, on_delete=models.CASCADE)
books_pc_multi_view2/models.py:    person = models.ForeignKey(Person, on_delete=models.CASCADE)

**Comment by rayed** [comment]
I believe Edward solve all of these problems, thank you both
